/**
 * Score fixtures for the codec suites.
 *
 * Copied from `music_lib`'s test tree when the codecs moved here, minus
 * `testRenderTheme` — that one needs a `RenderTheme`, and nothing in this
 * package renders anything.
 */

/**
 * Deterministic score fixtures shared across the test suite (Task 3 brief).
 * No randomness: ids are generated by a simple per-call counter (not
 * `createId`/`crypto.randomUUID`) and timestamps are a fixed constant, so
 * every call with the same arguments produces a structurally identical
 * `Score`.
 */
import type {
  KeySignature,
  Measure,
  NoteEvent,
  Pitch,
  PitchStep,
  Score,
  TimeSignature,
  Track,
} from "../index.js";
import { measureDurationTicks, ticksFor } from "../index.js";
import type { DurationName } from "../index.js";

const FIXED_TIMESTAMP = "2024-01-01T00:00:00.000Z";

/** A per-call, per-prefix incrementing id generator (deterministic, cheap). */
function makeIdFactory() {
  const counters = new Map<string, number>();
  return {
    next(prefix: string): string {
      const n = counters.get(prefix) ?? 0;
      counters.set(prefix, n + 1);
      return `${prefix}-${n}`;
    },
  };
}
type IdFactory = ReturnType<typeof makeIdFactory>;

type NoteSpec = { pitch: Pitch; duration: DurationName };

/** Builds consecutive single-voice melody measures from a per-measure list of note specs. */
function buildMelodyMeasures(
  measuresOfNotes: NoteSpec[][],
  ppq: number,
  timeSignature: TimeSignature,
  keySignature: KeySignature,
  trackId: string,
  ids: IdFactory,
): Measure[] {
  const measureTicks = measureDurationTicks(timeSignature, ppq);
  return measuresOfNotes.map((notes, index) => {
    const startTick = index * measureTicks;
    const voiceId = ids.next("voice");
    let cursor = startTick;
    const events: NoteEvent[] = notes.map((spec) => {
      const durationTicks = ticksFor(spec.duration, ppq);
      const event: NoteEvent = {
        id: ids.next("note"),
        pitch: spec.pitch,
        startTick: cursor,
        durationTicks,
        velocity: 80,
        voiceId,
        trackId,
      };
      cursor += durationTicks;
      return event;
    });
    return {
      id: ids.next("measure"),
      index,
      startTick,
      durationTicks: measureTicks,
      timeSignature,
      keySignature,
      voices: [{ id: voiceId, name: "Voice 1", events }],
    };
  });
}

/** Builds consecutive single-voice measures, each a block chord spanning the full measure. */
function buildChordMeasures(
  chordsByMeasure: Pitch[][],
  ppq: number,
  timeSignature: TimeSignature,
  keySignature: KeySignature,
  trackId: string,
  ids: IdFactory,
): Measure[] {
  const measureTicks = measureDurationTicks(timeSignature, ppq);
  return chordsByMeasure.map((pitches, index) => {
    const startTick = index * measureTicks;
    const voiceId = ids.next("voice");
    const events: NoteEvent[] = pitches.map((pitch) => ({
      id: ids.next("note"),
      pitch,
      startTick,
      durationTicks: measureTicks,
      velocity: 80,
      voiceId,
      trackId,
    }));
    return {
      id: ids.next("measure"),
      index,
      startTick,
      durationTicks: measureTicks,
      timeSignature,
      keySignature,
      voices: [{ id: voiceId, name: "Voice 1", events }],
    };
  });
}

const C_MAJOR: KeySignature = { fifths: 0, mode: "major" };
const FOUR_FOUR: TimeSignature = { numerator: 4, denominator: 4 };

function naturalPitch(step: PitchStep, octave: number): Pitch {
  return { step, accidental: 0, octave };
}

/** An 8-measure C-major "Twinkle Twinkle Little Star" melody on a single piano track. */
export function twinkleScore(): Score {
  const ids = makeIdFactory();
  const ppq = 480;

  const q = (step: PitchStep, octave = 4): NoteSpec => ({
    pitch: naturalPitch(step, octave),
    duration: "quarter",
  });
  const h = (step: PitchStep, octave = 4): NoteSpec => ({
    pitch: naturalPitch(step, octave),
    duration: "half",
  });

  const measures: NoteSpec[][] = [
    [q("C"), q("C"), q("G"), q("G")],
    [q("A"), q("A"), h("G")],
    [q("F"), q("F"), q("E"), q("E")],
    [q("D"), q("D"), h("C")],
    [q("G"), q("G"), q("F"), q("F")],
    [q("E"), q("E"), h("D")],
    [q("G"), q("G"), q("F"), q("F")],
    [q("E"), q("E"), h("D")],
  ];

  const trackId = ids.next("track");
  const track: Track = {
    id: trackId,
    name: "Piano",
    instrumentName: "Piano",
    midiProgram: 0,
    midiChannel: 0,
    clef: "treble",
    volume: 1,
    pan: 0,
    muted: false,
    solo: false,
    measures: buildMelodyMeasures(
      measures,
      ppq,
      FOUR_FOUR,
      C_MAJOR,
      trackId,
      ids,
    ),
  };

  return {
    id: ids.next("score"),
    version: 1,
    ppq,
    metadata: {
      title: "Twinkle Twinkle Little Star",
      createdAt: FIXED_TIMESTAMP,
      updatedAt: FIXED_TIMESTAMP,
    },
    tempoMap: [{ id: ids.next("tempo"), tick: 0, bpm: 120 }],
    tracks: [track],
  };
}

/** A 4-measure two-track score: a treble melody and a supporting bass line. */
export function twoTrackScore(): Score {
  const ids = makeIdFactory();
  const ppq = 480;

  const q = (step: PitchStep, octave: number): NoteSpec => ({
    pitch: naturalPitch(step, octave),
    duration: "quarter",
  });
  const w = (step: PitchStep, octave: number): NoteSpec => ({
    pitch: naturalPitch(step, octave),
    duration: "whole",
  });

  const trebleMeasures: NoteSpec[][] = [
    [q("C", 4), q("D", 4), q("E", 4), q("F", 4)],
    [q("G", 4), q("F", 4), q("E", 4), q("D", 4)],
    [q("C", 4), q("D", 4), q("E", 4), q("F", 4)],
    [q("G", 4), q("F", 4), q("E", 4), q("D", 4)],
  ];
  const bassMeasures: NoteSpec[][] = [
    [w("C", 2)],
    [w("G", 2)],
    [w("C", 2)],
    [w("G", 2)],
  ];

  const trebleId = ids.next("track");
  const bassId = ids.next("track");

  const treble: Track = {
    id: trebleId,
    name: "Treble",
    instrumentName: "Piano",
    midiProgram: 0,
    midiChannel: 0,
    clef: "treble",
    volume: 1,
    pan: 0,
    muted: false,
    solo: false,
    measures: buildMelodyMeasures(
      trebleMeasures,
      ppq,
      FOUR_FOUR,
      C_MAJOR,
      trebleId,
      ids,
    ),
  };
  const bass: Track = {
    id: bassId,
    name: "Bass",
    instrumentName: "Acoustic Bass",
    midiProgram: 32,
    midiChannel: 1,
    clef: "bass",
    volume: 1,
    pan: 0,
    muted: false,
    solo: false,
    measures: buildMelodyMeasures(
      bassMeasures,
      ppq,
      FOUR_FOUR,
      C_MAJOR,
      bassId,
      ids,
    ),
  };

  return {
    id: ids.next("score"),
    version: 1,
    ppq,
    metadata: {
      title: "Two Track Demo",
      createdAt: FIXED_TIMESTAMP,
      updatedAt: FIXED_TIMESTAMP,
    },
    tempoMap: [{ id: ids.next("tempo"), tick: 0, bpm: 120 }],
    tracks: [treble, bass],
  };
}

/**
 * Three tracks over 2 measures, deliberately plain.
 *
 * For tests about *which* tracks are involved — visibility, active-track
 * resolution, per-track filtering — where two tracks cannot tell "the first
 * one" apart from "the first visible one", and the music itself is beside the
 * point.
 */
export function threeTrackScore(): Score {
  const ids = makeIdFactory();
  const ppq = 480;

  const q = (step: PitchStep, octave: number): NoteSpec => ({
    pitch: naturalPitch(step, octave),
    duration: "quarter",
  });
  const measures: NoteSpec[][] = [
    [q("C", 4), q("D", 4), q("E", 4), q("F", 4)],
    [q("G", 4), q("F", 4), q("E", 4), q("D", 4)],
  ];

  const tracks: Track[] = ["Alpha", "Beta", "Gamma"].map((name, index) => {
    const trackId = ids.next("track");
    return {
      id: trackId,
      name,
      instrumentName: "Piano",
      midiProgram: 0,
      midiChannel: index,
      clef: "treble",
      volume: 1,
      pan: 0,
      muted: false,
      solo: false,
      measures: buildMelodyMeasures(
        measures,
        ppq,
        FOUR_FOUR,
        C_MAJOR,
        trackId,
        ids,
      ),
    };
  });

  return {
    id: ids.next("score"),
    version: 1,
    ppq,
    metadata: {
      title: "Three Track Demo",
      createdAt: FIXED_TIMESTAMP,
      updatedAt: FIXED_TIMESTAMP,
    },
    tempoMap: [{ id: ids.next("tempo"), tick: 0, bpm: 120 }],
    tracks,
  };
}

/**
 * Two tracks with sharply different densities: a treble line of 16
 * sixteenth notes per measure over a bass of one whole note per measure.
 * Exercises cross-track timeline sync — the dense track needs a wider
 * measure than `BASE_MEASURE_WIDTH` and must still share barlines and
 * tick-aligned x positions with the sparse track.
 */
export function denseVsSparseScore(): Score {
  const ids = makeIdFactory();
  const ppq = 480;

  const s = (step: PitchStep, octave: number): NoteSpec => ({
    pitch: naturalPitch(step, octave),
    duration: "sixteenth",
  });
  const w = (step: PitchStep, octave: number): NoteSpec => ({
    pitch: naturalPitch(step, octave),
    duration: "whole",
  });

  const runUp: NoteSpec[] = (["C", "D", "E", "F", "G", "A", "B"] as PitchStep[])
    .flatMap((step) => [s(step, 4), s(step, 4)])
    .concat([s("C", 5), s("C", 5)]);
  const denseMeasures: NoteSpec[][] = [runUp, runUp, runUp, runUp];
  const sparseMeasures: NoteSpec[][] = [
    [w("C", 2)],
    [w("G", 2)],
    [w("C", 2)],
    [w("G", 2)],
  ];

  const denseId = ids.next("track");
  const sparseId = ids.next("track");

  const dense: Track = {
    id: denseId,
    name: "Dense",
    instrumentName: "Piano",
    midiProgram: 0,
    midiChannel: 0,
    clef: "treble",
    volume: 1,
    pan: 0,
    muted: false,
    solo: false,
    measures: buildMelodyMeasures(
      denseMeasures,
      ppq,
      FOUR_FOUR,
      C_MAJOR,
      denseId,
      ids,
    ),
  };
  const sparse: Track = {
    id: sparseId,
    name: "Sparse",
    instrumentName: "Acoustic Bass",
    midiProgram: 32,
    midiChannel: 1,
    clef: "bass",
    volume: 1,
    pan: 0,
    muted: false,
    solo: false,
    measures: buildMelodyMeasures(
      sparseMeasures,
      ppq,
      FOUR_FOUR,
      C_MAJOR,
      sparseId,
      ids,
    ),
  };

  return {
    id: ids.next("score"),
    version: 1,
    ppq,
    metadata: {
      title: "Dense vs Sparse",
      createdAt: FIXED_TIMESTAMP,
      updatedAt: FIXED_TIMESTAMP,
    },
    tempoMap: [{ id: ids.next("tempo"), tick: 0, bpm: 120 }],
    tracks: [dense, sparse],
  };
}

/** A 4-measure I-IV-V-I block-chord progression on a single piano track. */
export function chordScore(): Score {
  const ids = makeIdFactory();
  const ppq = 480;

  const chords: Pitch[][] = [
    [naturalPitch("C", 4), naturalPitch("E", 4), naturalPitch("G", 4)], // I
    [naturalPitch("F", 4), naturalPitch("A", 4), naturalPitch("C", 5)], // IV
    [naturalPitch("G", 4), naturalPitch("B", 4), naturalPitch("D", 5)], // V
    [naturalPitch("C", 4), naturalPitch("E", 4), naturalPitch("G", 4)], // I
  ];

  const trackId = ids.next("track");
  const track: Track = {
    id: trackId,
    name: "Piano",
    instrumentName: "Piano",
    midiProgram: 0,
    midiChannel: 0,
    clef: "treble",
    volume: 1,
    pan: 0,
    muted: false,
    solo: false,
    measures: buildChordMeasures(chords, ppq, FOUR_FOUR, C_MAJOR, trackId, ids),
  };

  return {
    id: ids.next("score"),
    version: 1,
    ppq,
    metadata: {
      title: "Chord Progression Demo",
      createdAt: FIXED_TIMESTAMP,
      updatedAt: FIXED_TIMESTAMP,
    },
    tempoMap: [{ id: ids.next("tempo"), tick: 0, bpm: 90 }],
    tracks: [track],
  };
}

const STRESS_SCALE: PitchStep[] = ["C", "D", "E", "F", "G", "A", "B"];

/**
 * Generates a score with `trackCount` tracks of `measureCount` measures
 * each (4 quarter notes per measure, cycling through a C-major scale), for
 * performance/stress tests. Deterministic and allocation-light.
 */
export function stressScore(trackCount: number, measureCount: number): Score {
  const ids = makeIdFactory();
  const ppq = 480;
  const measureTicks = measureDurationTicks(FOUR_FOUR, ppq);
  const quarterTicks = ticksFor("quarter", ppq);

  const tracks: Track[] = [];
  for (let t = 0; t < trackCount; t += 1) {
    const trackId = ids.next("track");
    const measures: Measure[] = [];
    for (let m = 0; m < measureCount; m += 1) {
      const startTick = m * measureTicks;
      const voiceId = ids.next("voice");
      const events: NoteEvent[] = [];
      for (let beat = 0; beat < 4; beat += 1) {
        const step = STRESS_SCALE[(t + m + beat) % STRESS_SCALE.length];
        events.push({
          id: ids.next("note"),
          pitch: naturalPitch(step, 4),
          startTick: startTick + beat * quarterTicks,
          durationTicks: quarterTicks,
          velocity: 80,
          voiceId,
          trackId,
        });
      }
      measures.push({
        id: ids.next("measure"),
        index: m,
        startTick,
        durationTicks: measureTicks,
        timeSignature: FOUR_FOUR,
        keySignature: C_MAJOR,
        voices: [{ id: voiceId, name: "Voice 1", events }],
      });
    }
    tracks.push({
      id: trackId,
      name: `Track ${t + 1}`,
      instrumentName: "Piano",
      midiProgram: 0,
      midiChannel: t % 16,
      clef: "treble",
      volume: 1,
      pan: 0,
      muted: false,
      solo: false,
      measures,
    });
  }

  return {
    id: ids.next("score"),
    version: 1,
    ppq,
    metadata: {
      title: `Stress ${trackCount}x${measureCount}`,
      createdAt: FIXED_TIMESTAMP,
      updatedAt: FIXED_TIMESTAMP,
    },
    tempoMap: [{ id: ids.next("tempo"), tick: 0, bpm: 120 }],
    tracks,
  };
}
